### ISSUE TITLE
Tomcat 8.5 application dataSources not displayed in Probe 3.0.1

### ISSUE THREAD

**Issue by robertoschwald** [psi-probe/psi-probe#1210]
Configured a dataSource Resource in applications context.xml (and using it).

Probe does not detect the DS.

Testing here with Probe 3.1.0, Tomcat 8.5.29, OpenJDK 1.8.0_191.

"There are no data sources configured for this Tomcat instance"

Log:
```
[psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/my_datasource
[psiprobe.beans.ResourceResolverBean] reading resource jndi name: java:comp/env/jdbc/my_datasource
```

**Comment by hazendaz** [comment]
Make sure your database driver is in tomcat lib

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by robertoschwald** [comment]
DB driver is in lib dir (otherwise tomcat would throw an exception on application loading. It is a Tomcat datasource resource).

**Comment by hazendaz** [comment]
@robertoschwald Can you provide a sanitized example of the issue you are facing?  Maybe even a sample project would be of great help to track this down.  Or if you happen to know where the issue is in the code, a pull request would be greatly appreciated.

**Comment by pizzit** [comment]
Same problem with probe v3.3.0 on Tomcat 8.5.41 / Java 8.212

It was ok with probe v.3.2.0 ... !

tomcat/lib contain the following libraries:
- HikariCP-3.3.1
- mariadb-java-client-2.4.2

webapp resource configured with context.xml:


` <Resource name="jdbc/dbDatasource" auth="Container" 
                      type="javax.sql.DataSource"
 		      factory="com.zaxxer.hikari.HikariJNDIFactory"
 		      minimumIdle="2" maximumPoolSize="4" 
           	      driverClassName="org.mariadb.jdbc.Driver"           	
           	      autoCommit="false"
           	      registerMbeans="true"
           	      closeMethod="close"
           	      username="xxx" password="xxx" 
	              jdbcUrl="jdbc:mariadb://127.0.0.1:3306/db?useUnicode=true" /> `

**Comment by robertoschwald** [comment]
Same problem here with Tomcat 8.5.29, Psi Probe 3.3.1.

Have a datasource defined in conf/Catalina/localhost/myapp.xml like this:
```
<Resource name="jdbc/example_ds"
  auth="Container" type="javax.sql.DataSource"
        factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
        driverClassName="com.mysql.jdbc.Driver"
        initialSize="5"
        maxActive="200"
        minIdle="10"
        maxIdle="30"
        maxWait="60000"
        maxAge="1800000"
       username="demo"
       password="demo"
       alidationQuery="select 1"
        validationQueryTimeout="3"
        validationInterval="30000"
        timeBetweenEvictionRunsMillis="30000"
        minEvictableIdleTimeMillis="30000"
        testWhileIdle="true"
        testOnBorrow="true"
        testOnReturn="false"
        removeAbandoned="true"
        removeAbandonedTimeout="86400"
        abandonWhenPercentageFull="0"
        logAbandoned="true"
       jdbcInterceptors="ConnectionState;StatementFinalizer;ResetAbandonedTimer"
       url="jdbc:mysql://127.0.0.1:3306/demodb" />
```

**Comment by robertoschwald** [comment]
<img width="668" alt="no_ds" src="https://user-images.githubusercontent.com/1519879/71162092-d84bec00-224a-11ea-8635-8722a2cd5730.png">

**Comment by pizzi80** [comment]
Using the same stack and datasource configuration (see my previous reply) 
on Tomcat 8.5.41 and Tomcat 8.5.45 these are the results:

PSI Probe v3.2.0  show datasources details

PSI Probe v3.3.0 - v.3.3.1 - v3.4.2  doesn't work

what's changed in Probe regarding datasources discovery?

**Comment by hazendaz** [comment]
@pizzi80 @robertoschwald The only thing that has changed in respect to anything related to jdbc since psi probe 3.2.0 is dependencies.  You can find diff [here](https://github.com/psi-probe/psi-probe/compare/3.2.0...master)  No source code has changed in relation to jdbc.  Its possible one of the libraries is causing your issue.  You might want to look at what has changed and try to change back some dependencies associated with that support.

**Comment by hazendaz** [comment]
@pizzi80 Can you try building from current master and see if behaviour is any different?  There was a hikari library picked up from quartz that was ending up incorrectly in the built war.  I'm not sure if that will make a difference but it did show up after 3.2.0 release.

**Comment by pizzi80** [comment]
@hazendaz it works!!

I've downloaded the following version and now it's working as expected!

psi-probe-web-3.4.3-20200107.053530-19.war

thanks

**Comment by hazendaz** [comment]
Great thanks for checking.  I should have that released in the next week or so.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
This was resolved.  Closing.

**Comment by robertoschwald** [comment]
Sorry to say, but it still does not work when using version 3.4.5 on Tomcat 8.5.29.

Log sais:
`INFO psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/xxx`

but in the datasource ui:

`There are no data sources configured for this Tomcat instance` 

Still the same config as posted at 2019-12-19

**Comment by hazendaz** [comment]
Hi @robertoschwald, @pizzi80 Stated it was fixed with 3.4.3.  I can look again but noted resolution, can you try the point in time build @pizzi80 did and see if that works?  Its possible another library change came in as some third parties seem to keep adding lessage versions.   I'd have to look but had not heard otherwise after the original fix until now.

**Comment by robertoschwald** [comment]
@hazendaz Where can I get the version from? https://oss.sonatype.org/content/repositories/snapshots/com/github/psi-probe/psi-probe-web/3.4.3-SNAPSHOT/ does not hold this version anymore.

**Comment by hazendaz** [comment]
commit  1d46b90252f7bff3313e1cbacc1378921f11c344 was when I noted I thought it was fixed.  I know @pizzi80 tested off january 7th build and it was working then.  You might want to check this commit out and build locally and see what you get.  I'll take a look at more recent dependency tree again and see if anything seeped in.

**Comment by robertoschwald** [comment]
Tried out version 1d46b90 (Commit of 25.12.2019).
Does not work. Still "There are no data sources configured for this Tomcat instance".

Logs:

15:14:00.032 INFO  {Probe_Quartz-4} [psiprobe.beans.ContainerWrapperBean] Using DEFAULT resource resolver
15:14:00.043 INFO  {Probe_Quartz-4} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/xxx
15:14:09.143 INFO  {ajp-nio-9009-exec-3} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/xxx
15:14:09.837 INFO  {ajp-nio-9009-exec-3} [org.displaytag.export.ExportViewFactory] Initializing ExportViewFactory with type={xml}
15:14:09.845 INFO  {ajp-nio-9009-exec-3} [o.displaytag.properties.TableProperties] LocaleResolver initialized to org.displaytag.localization.I18nSpringAdapter.
15:14:09.889 INFO  {ajp-nio-9009-exec-3} [o.displaytag.properties.TableProperties] I18nResourceProvider initialized to org.displaytag.localization.I18nSpringAdapter.
15:14:12.932 INFO  {ajp-nio-9009-exec-12} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/xxx


I then enabled debug logs.

[TC_8.5.29_1d46b90_debug.txt](https://github.com/psi-probe/psi-probe/files/4438612/TC_8.5.29_1d46b90_debug.txt)

**Comment by robertoschwald** [comment]
I enable trace logging of the ResourceResolverBean and see this (latest master snapshot d410f5ab4253d1e28a0c8f5c410433cb4f3cebe3). Don't know if it is related.
Maybe you re-open the issue?
 

```
19:46:38.085 TRACE {ajp-nio-9009-exec-9} [psiprobe.beans.ResourceResolverBean] JMX objectName tomcat.jdbc:type=Server does not contain any managedResource
javax.management.InstanceNotFoundException: tomcat.jdbc:type=Server
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at psiprobe.beans.ResourceResolverBean.getGlobalNamingContext(ResourceResolverBean.java:331)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:148)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:84)
	at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:236)
	at psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequestInternal(ListAllJdbcResourcesController.java:46)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequest(ListAllJdbcResourcesController.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
